### ISSUE TITLE
【BUG】show.py运行报错

### ISSUE THREAD

**Issue by RibomBalt** [chbpku/pingpong.sessdsa#19]
```
C:\Users\Cobalt-YangFan\AppData\Local\Programs\Python\Python35\python.exe C:/Users/Cobalt-YangFan/PycharmProjects/Final-Homework-SESSDSA/show.py
Traceback (most recent call last):
  File "C:\Users\Cobalt-YangFan\AppData\Local\Programs\Python\Python35\lib\shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Cobalt-YangFan/PycharmProjects/Final-Homework-SESSDSA/show.py", line 190, in <module>
    main()
  File "C:/Users/Cobalt-YangFan/PycharmProjects/Final-Homework-SESSDSA/show.py", line 121, in main
    log = readlog(logname)
  File "C:/Users/Cobalt-YangFan/PycharmProjects/Final-Homework-SESSDSA/show.py", line 38, in readlog
    log = d['log']
  File "C:\Users\Cobalt-YangFan\AppData\Local\Programs\Python\Python35\lib\shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
  File "C:\Users\Cobalt-YangFan\AppData\Local\Programs\Python\Python35\lib\dbm\dumb.py", line 141, in __getitem__
    pos, siz = self._index[key]     # may raise KeyError
KeyError: b'log'

Process finished with exit code 1
```
首先运行pingpong.py，然后运行show.py，报错如上。

**Comment by planetarianPKU** [comment]
请附上·源代码和对战文件名称。show.py第116行左右的文件名须改成对战生成的文件名。
我一开始也是报错Keyerror,改后能运行了

**Comment by RibomBalt** [comment]
![image](https://cloud.githubusercontent.com/assets/26453381/26285499/eee2eac0-3e83-11e7-8c81-7edde9b44544.png)
用默认设置的话应该没有问题的
源代码和现在的 commit: 45fd6a3 保持一致

**Comment by planetarianPKU** [comment]
不一定……比如想复盘'[E.L]T_idiot-VS-T_idiot'，就需要手动改一下……默认的设置只是其中一种情况（好像是W.T？）……而且说实在的我一开始跟你的报错一模一样hhh

**Comment by alleriawr9** [comment]
解决了，118行前缀两个大写字母要改，改成几k以上大小的那个

**Comment by RibomBalt** [comment]
明白了，默认值是需要改动的。交给我吧。
